name: Run Issue Scouter

on:
  push:
    branches:
      - '*'

jobs:
  run-issue-scouter:
    runs-on: ubuntu-latest
    steps:
      - name: Run Issue Scouter
        uses: ymtdzzz/issue-scouter@7fa222bed5110b8815cc4584bf7bd70d5c83ff63
        with:
          dry-run: "true"
          config_file: "config.yml"
