name: Run Issue Scouter

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  run-issue-scouter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Issue Scouter
        uses: ymtdzzz/issue-scouter@v0.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: "false"
          config_file: "config.yml"
